version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"


  rabbitmq-publisher:
    image: rabbitmq-publisher  #HINT: to build this docker image, use the Dockerfile which exists in the following folder /docker/rabbitmq-publisher/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 5

  backendserver:
    # https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0
    # export command is added to avoid the following error
    # ERROR: Service 'backendserver' failed to build : Get "https://registry-1.docker.io/v2/": dial tcp: 
    # lookup registry-1.docker.io on 192.168.65.5:53: read udp 192.168.65.4:60859->192.168.65.5:53: i/o timeout
    command: > 
      bash -c "export DOCKER_BUILDKIT=0 &&
      export COMPOSE_DOCKER_CLI_BUILD=0"
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
           - "8080:8080"
    restart: always
